-- MySQL Script generated by MySQL Workbench
-- Tue Apr  2 16:14:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projekt_chmura
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projekt_chmura` ;

-- -----------------------------------------------------
-- Schema projekt_chmura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projekt_chmura` DEFAULT CHARACTER SET utf8 ;
USE `projekt_chmura` ;

-- -----------------------------------------------------
-- Table `projekt_chmura`.`uzytkownicy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekt_chmura`.`uzytkownicy` ;

CREATE TABLE IF NOT EXISTS `projekt_chmura`.`uzytkownicy` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `haslo` VARCHAR(128) NOT NULL,
  `admin` BIT(1) NOT NULL DEFAULT 0,
  `miejsce` INT(7) NOT NULL DEFAULT 50,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_chmura`.`pliki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekt_chmura`.`pliki` ;

CREATE TABLE IF NOT EXISTS `projekt_chmura`.`pliki` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazwa` VARCHAR(100) NOT NULL
  `plik` LONGBLOB NOT NULL,
  `kod` VARCHAR(20) NULL,
  `wlasciciel` INT NOT NULL,
  PRIMARY KEY (`id`, `wlasciciel`),
  INDEX `fk_pliki_uzytkownicy_idx` (`wlasciciel` ASC) ,
  CONSTRAINT `fk_pliki_uzytkownicy`
    FOREIGN KEY (`wlasciciel`)
    REFERENCES `projekt_chmura`.`uzytkownicy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_chmura`.`rejestracja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekt_chmura`.`rejestracja` ;

CREATE TABLE IF NOT EXISTS `projekt_chmura`.`rejestracja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(64) NOT NULL,
  `kod` VARCHAR(20) NOT NULL,
  `czas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_chmura`.`blokada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekt_chmura`.`blokada` ;

CREATE TABLE IF NOT EXISTS `projekt_chmura`.`blokada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(15) NOT NULL,
  `czas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projekt_chmura`.`blokada2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projekt_chmura`.`blokada2` ;

CREATE TABLE IF NOT EXISTS `projekt_chmura`.`blokada2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(15) NOT NULL,
  `czas` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
